name: EasyPrefix
version: 1.6.5_ALPHA
author: Christian34
main: com.christian34.easyprefix.EasyPrefix
api-version: "1.13"
softdepend:
  - PlaceholderAPI
  - Vault
  - Venture
loadbefore:
  - MultiChatSpigot
commands:
  EasyPrefix:
    description: Main command
    aliases: [ep, easyp, eprefix]