name: EasyPrefix
version: 1.6.5_ALPHA
author: Christian34
main: com.christian34.easyprefix.EasyPrefix
api-version: "1.15"
softdepend:
  - PlaceholderAPI
  - Vault

commands:
  EasyPrefix:
    description: Main command
    aliases: [ep, easyp, eprefix]